jira:
    url: ${JIRA_URL}

holiday:
  url: https://api.calendario.com.br/?json=true&token=
  token: ${HOLIDAY_TOKEN}

spring:
  application:
    name: jirareport
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:5432/jirareport
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    out-of-order: true
    ignore-missing-migrations: true
